services:
  ollama:
    image: ollama/ollama:0.9.2
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data
    restart: unless-stopped

  neo4j:
    image: neo4j:5.19
    container_name: neo4j
    ports:
      - "8080:7474"   # HTTP UI
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  huggingface-embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
    container_name: huggingface-embeddings
    ports:
      - "9000:80"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - MODEL_ID=${EMBEDDING_MODEL:-sentence-transformers/msmarco-MiniLM-L6-v3}
      #- MODEL_ID=sentence-transformers/all-MiniLM-L12-v2-2048
      #- MODEL_ID=FacebookAI/xlm-mlm-en-2048
      #- MODEL_ID=Snowflake/snowflake-arctic-embed-m-v2.0
      #- MODEL_ID=Qwen/Qwen3-Embedding-0.6B
      #- MODEL_ID=sentence-transformers/sentence-t5-xxl
      #- MODEL_ID=/data/BAAI/bge-base_en_v1.5
      # - DEVICE=cpu
    volumes:
      - huggingface_data:/data
      #- ${HOME}/embedding-models:/data
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
    name: ollama_data
  chroma_data:
    driver: local
    name: chroma_data
  neo4j_data:
    driver: local
    name: neo4j_data
  huggingface_data:
    driver: local
    name: huggingface_data
